### PR TITLE
BUGFIX: set unique form element identifier after node copy

### LINKED ISSUE #44: Copy a form element with an identifier set leads to an exception and breaks future editing
### Description

[Description of the bug or feature]
If i copy and paste a form-element with an identifier (ex: budget) set, i get the exception `A form element with identifier "budget" is already part of the form` which seems legit…
BUT im not able to edit the form because the exception “breaks” the Content Tree..

image

### Steps to Reproduce

1. Add a Form Element
2. Set an Identifier
3. Copy the Element
4. Paste the Element
5. Exception 💥

#### Expected behavior
There are many options, maybe a Modal where u have to set a new identifier (like page creation) or same as in the uriPathSegment where `-1` is added to the identifier?

### Affected Versions
Neos: 4.3

### PR DESCRIPTION
**Pull request by ger4003**
When a form element with identifier propery is copied an exception is thrown.
@see https://github.com/neos/form/blob/3a6122db36ad2c9e6f06316653a35c80ff47dee1/Classes/Core/Model/FormDefinition.php#L553

This changes adds a signal slot for \Neos\ContentRepository\Domain\Model\Node 
~`afterNodeCopy`~ `addedNode` to make the form element identifier unique. This also works if a whole section having a form element with identifier is copied and inserted.

Fixes #44

### CODE REVIEW

File: Classes/Package.php [hunk 1]
```diff
@@ -12,6 +12,8 @@
  */
 class Package extends BasePackage
 {
+    const NODE_TYPE_IDENTIFIER_MIXIN = 'Neos.Form.Builder:IdentifierMixin';
```
Comment (bwaidelich) [inline Classes/Package.php:15]: good call to make this a constant, but IMO it should be private
```suggestion
    private const NODE_TYPE_IDENTIFIER_MIXIN = 'Neos.Form.Builder:IdentifierMixin';
```

File: Classes/Package.php [hunk 2]
```diff
@@ -21,23 +23,52 @@ public function boot(Bootstrap $bootstrap)
         $dispatcher = $bootstrap->getSignalSlotDispatcher();
 
         $dispatcher->connect(Node::class, 'nodePropertyChanged', function (NodeInterface $node, $propertyName, $_, $newValue) use ($bootstrap) {
```
Comment (bwaidelich) [inline Classes/Package.php:25]: not new but it should be fixed IMO: `$bootstrap` is not used in the closure
```suggestion
        $dispatcher->connect(Node::class, 'nodePropertyChanged', function (NodeInterface $node, $propertyName, $_, $newValue) {
```

File: Classes/Package.php [hunk 3]
```diff
@@ -21,23 +23,52 @@ public function boot(Bootstrap $bootstrap)
...
-            while ($flowQuery
-                    ->closest('[instanceof Neos.Form.Builder:NodeBasedForm]')
-                    // [identifier=".."] matches the Form Element identifier, [_identiier!="..."] excludes the current node
-                    ->find(sprintf('[instanceof Neos.Form.Builder:IdentifierMixin][identifier="%s"][_identifier!="%s"]', $possibleIdentifier, $node->getIdentifier()))
-                    ->count() > 0) {
-                $possibleIdentifier = $initialIdentifier . '-' . $i++;
+            $this->setUniqueFormElementIdentifier($node, $newValue);
+        });
+
+        $dispatcher->connect(Node::class, 'nodeAdded', function (NodeInterface $node) use ($bootstrap) {
```
Comment (bwaidelich) [inline Classes/Package.php:33]: `$bootstrap` is not used by the closure:
```suggestion
        $dispatcher->connect(Node::class, 'nodeAdded', function (NodeInterface $node) {
```

File: Classes/Package.php [hunk 4]
```diff
@@ -21,23 +23,52 @@ public function boot(Bootstrap $bootstrap)
...
+            $this->setUniqueFormElementIdentifier($node, $identifier);
         });
     }
+
+    /**
+     * @param NodeInterface $node
+     * @param string $identifier
+     * @throws \Neos\Eel\Exception
+     */
+    protected function setUniqueFormElementIdentifier(NodeInterface $node, string $identifier): void
```
Comment (bwaidelich) [inline Classes/Package.php:53]: This is not meant to be extensible, is it?
```suggestion
    private function setUniqueFormElementIdentifier(NodeInterface $node, string $identifier): void
```

**Comment by bwaidelich** [comment]
Ah one additional comment: I think this is a *BUGFIX*  rather than a *FEATURE* (making it eligible for a patch level release

**Comment by ger4003** [comment]
Thanks @bwaidelich for the review. I adjusted the code.
